name = "v2raymoein"
main = "src/worker.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "settings", id = "1071f142071b4b0bb48753aafffdcbf7" }
]
